// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3QlZzBwpwnQOFA-hg3GoT6Zp249VdUo',
    appId: '1:120240986296:web:93437da5bd2f2189833c4d',
    messagingSenderId: '120240986296',
    projectId: 'chat-app-getx-24df5',
    authDomain: 'chat-app-getx-24df5.firebaseapp.com',
    storageBucket: 'chat-app-getx-24df5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8llulQvl0k07p4RpblTf-Rb6BzLXPqQ',
    appId: '1:120240986296:android:cd02f8669f5df4c4833c4d',
    messagingSenderId: '120240986296',
    projectId: 'chat-app-getx-24df5',
    storageBucket: 'chat-app-getx-24df5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoV-Zda7Si5TvBthW6BQ1sRIN8y0t9Llw',
    appId: '1:120240986296:ios:87f27ae16a5fa686833c4d',
    messagingSenderId: '120240986296',
    projectId: 'chat-app-getx-24df5',
    storageBucket: 'chat-app-getx-24df5.appspot.com',
    iosClientId:
        '120240986296-s16bjghpro7bsd42c9i4dd8jk7lbm3ci.apps.googleusercontent.com',
    iosBundleId: 'com.netscaledigital.getChat',
  );
}
